//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace furnitare
{
    using System;
    using System.Collections.Generic;
    
    public partial class Furniture
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Furniture()
        {
            this.Sklad = new HashSet<Sklad>();
        }
    
        public int Id_Furniture { get; set; }
        public int Id_Postavshik { get; set; }
        public int id_TypeFurniture { get; set; }
        public int Id_Material { get; set; }
        public int Id_Proizvoditel { get; set; }
        public Nullable<decimal> Цена { get; set; }
        public string Название { get; set; }
        public Nullable<int> Количество { get; set; }
    
        public virtual Material Material { get; set; }
        public virtual Postavshik Postavshik { get; set; }
        public virtual Proizvoditel Proizvoditel { get; set; }
        public virtual TypeFurniture TypeFurniture { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sklad> Sklad { get; set; }
    }
}
