//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace furnitare
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shop
    {
        public int Id_Shop { get; set; }
        public int Id_Sklad { get; set; }
        public int Id_Sotrudnik { get; set; }
        public string Адресс { get; set; }
        public Nullable<decimal> ТелНомер { get; set; }
    
        public virtual Sklad Sklad { get; set; }
        public virtual Sotrudnik Sotrudnik { get; set; }
    }
}
