//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace furnitare
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int ID { get; set; }
        public int Id_Sotrudniki { get; set; }
        public int Id_Doljnost { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
    
        public virtual Doljnost Doljnost { get; set; }
        public virtual Sotrudniki Sotrudniki { get; set; }
    }
}
